name: Main workflow

on:
  - push
  - pull_request

jobs:
  build:
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        ocaml-version:
          - 4.04.2
          - 4.05.0
          - 4.06.1
          - 4.07.1
          - 4.08.1
          - 4.09.1

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Try to restore opam cache
        if: runner.os != 'Windows'
        id: opam-cache
        uses: actions/cache@v2
        with:
          path: "~/.opam"
          key: ${{ matrix.os }}-${{ matrix.ocaml-version }}

      - name: Try to restore opam cache
        if: runner.os == 'Windows'
        id: opam-cache-windows
        uses: actions/cache@v2
        with:
          path: "/home/runneradmin/.opam"
          key: ${{ matrix.os }}-a${{ matrix.ocaml-version }}

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - name: Get opam root path
        id: opam
        run: echo "$(opam var root)"

      - name: Try to restore build cache
        id: build-cache
        uses: actions/cache@v2
        with:
          path: "_build"
          key: ${{ matrix.os }}-${{ matrix.ocaml-version }}

      - run: opam install . --deps-only --with-doc --with-test

      - run: opam exec -- dune build

      - run: opam exec -- dune runtest
